### ISSUE TITLE
The government should not use TV as an excuse for 茶餐廳牌照 and it should give 香港餐蛋麵娛樂 a license

### ISSUE THREAD

**Issue by whhone** [david90/procedure-fairness-report-generator#2]
In "政府進一步闡釋行會就茶餐廳牌照申請的決定", http://bit.ly/179UAny.

"在考慮公眾利益時，行會認為茶餐廳市場的可持續和穩健發展是重要考慮因素。因此應循序漸進地引入競爭，**_以免因免費電視台急劇增加而造成負面影響**_，例如割喉式競爭以致餐蛋麵質素下降，最終令公眾得不償失。"

**_以免因免費電視台急劇增加而造成負面影響**_
**_以免因免費電視台急劇增加而造成負面影響**_
**_以免因免費電視台急劇增加而造成負面影響**_

The government should not use TV as an excuse.
It should give a license to 香港餐蛋麵娛樂.

**Comment by david90** [comment]
I agree, @whhone 
The document changes without your notice :o)

**Comment by whhone** [comment]
Thanks.
